name: 🐦 Compile and Release Whee

on:
  push:
    tags:
      - 'v*'  # Automatic trigger on version tags like v0.1.0, v1.2.3, etc.
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release tag (e.g., v1.2.3)'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    name: 🏗️ Build
    runs-on: ubuntu-latest

    steps:
      - name: 📃 Checkout Repository
        uses: actions/checkout@v4

      - name: 📝 Create bin/ directory
        run: |
          rm -rf bin
          mkdir -p bin

      - name: 🏗️ Compile
        run: cargo build --release

      - name: 📁 Move to bin
        run: |
            mv target/release/whee bin/
            mv target/release/wheec bin/

  release:
    name: 📤 Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: 📃 Checkout Repository
        uses: actions/checkout@v4

      - name: 📝 Determine Tag Name
        id: get_tag
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "tag_name=${{ github.event.inputs.tag_name }}" >> "$GITHUB_OUTPUT"
          else
            echo "tag_name=${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
          fi

      - name: 🏷️ Create Tag (only for manual runs)
        if: github.event_name == 'workflow_dispatch'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag ${{ steps.get_tag.outputs.tag_name }}
          git push origin ${{ steps.get_tag.outputs.tag_name }}

      - name: 📤 Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_tag.outputs.tag_name }}
          name: Release ${{ steps.get_tag.outputs.tag_name }}
          body: |
            This is an automated release of Whee.
            Binaries have been compiled but are **not** attached to this release.
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
